# Generated by Django 4.2.7 on 2023-11-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
    ]
